/**
 * Per-locale split file generation for i18n collections.
 *
 * When outputStrategy is "split", generates:
 * - _types.ts: shared TypeScript interfaces
 * - {locale}/{collection}.ts: data for one locale only
 * - {locale}/index.ts: re-exports all collections for that locale
 * - _locale.ts: async locale() resolver with fallback chain
 * - index.ts: re-exports types + locale utility
 */

import fs from "node:fs/promises";
import path from "node:path";
import type { ZodTypeAny } from "zod";
import { generateTypeFromZod, type I18nCollectionData } from "./generator.js";

// ── Types ───────────────────────────────────────────────────────────────────

export interface SplitCollectionMeta {
  name: string;
  metaTypeName: string;
  entryTypeName: string;
  schema?: ZodTypeAny;
}

// ── Shared types file (_types.ts) ───────────────────────────────────────────

/**
 * Generate _types.ts with shared interfaces for all collections.
 */
export async function generateSharedTypesFile(
  outputDir: string,
  collections: SplitCollectionMeta[]
): Promise<void> {
  let output = `// Auto-generated by contenz - DO NOT EDIT\n// Run: contenz build\n\n`;

  for (const col of collections) {
    if (col.schema) {
      output += generateTypeFromZod(col.schema, col.metaTypeName);
      output += "\n\n";
    } else {
      output += `export interface ${col.metaTypeName} {\n  [key: string]: unknown;\n}\n\n`;
    }

    output += `/** ${col.name} entry with file path and all metadata */\n`;
    output += `export interface ${col.entryTypeName} extends ${col.metaTypeName} {\n`;
    output += `  slug: string;\n`;
    output += `  file: string;\n`;
    output += `  _fallback?: string;\n`;
    output += `}\n\n`;
  }

  await fs.writeFile(path.join(outputDir, "_types.ts"), output, "utf-8");
}

// ── Per-locale collection file ({locale}/{collection}.ts) ───────────────────

/**
 * Resolve locale with chained fallback support.
 */
function resolveLocaleChain(
  locales: Record<string, { file: string; meta: Record<string, unknown> }>,
  locale: string,
  fallbackMap: Record<string, string>,
  maxDepth = 5
): { file: string; meta: Record<string, unknown>; _fallback?: string } | null {
  // Direct hit
  if (locales[locale]) return { file: locales[locale].file, meta: locales[locale].meta };

  // Chain fallback
  let current = fallbackMap[locale] ?? fallbackMap.__default;
  const visited = new Set<string>([locale]);
  while (current && !visited.has(current) && visited.size < maxDepth) {
    visited.add(current);
    if (locales[current]) {
      return { file: locales[current].file, meta: locales[current].meta, _fallback: current };
    }
    current = fallbackMap[current] ?? fallbackMap.__default;
  }
  return null;
}

/**
 * Generate a single locale file: {locale}/{collection}.ts
 */
export async function generateSplitLocaleCollectionFile(
  outputDir: string,
  locale: string,
  collectionName: string,
  items: I18nCollectionData[],
  entryTypeName: string,
  fallbackMap: Record<string, string>,
  includeFallbackMetadata: boolean
): Promise<void> {
  const localeDir = path.join(outputDir, locale);
  await fs.mkdir(localeDir, { recursive: true });

  let output = `// Auto-generated by contenz - DO NOT EDIT\n`;
  output += `import type { ${entryTypeName} } from "../_types.js";\n\n`;

  const dataObj: Record<string, unknown> = {};
  for (const item of items) {
    const resolved = resolveLocaleChain(item.locales, locale, fallbackMap);
    if (!resolved) continue;

    const entry: Record<string, unknown> = {
      slug: item.slug,
      file: resolved.file,
      ...resolved.meta,
    };
    if (includeFallbackMetadata && resolved._fallback) {
      entry._fallback = resolved._fallback;
    }

    dataObj[item.slug] = entry;
  }

  output += `export const ${collectionName}: Record<string, ${entryTypeName}> = `;
  output += JSON.stringify(dataObj, null, 2);
  output += ";\n\n";

  output += `export const ${collectionName}Slugs = Object.keys(${collectionName}) as (keyof typeof ${collectionName})[];\n`;

  await fs.writeFile(path.join(localeDir, `${collectionName}.ts`), output, "utf-8");
}

// ── Per-locale index file ({locale}/index.ts) ───────────────────────────────

/**
 * Generate {locale}/index.ts that re-exports all collections for that locale.
 */
export async function generateLocaleIndexFile(
  outputDir: string,
  locale: string,
  collections: { name: string }[]
): Promise<void> {
  let output = `// Auto-generated by contenz - DO NOT EDIT\n\n`;

  for (const col of collections) {
    output += `export { ${col.name}, ${col.name}Slugs } from "./${col.name}.js";\n`;
  }

  await fs.writeFile(path.join(outputDir, locale, "index.ts"), output, "utf-8");
}

// ── Locale resolver (_locale.ts) ────────────────────────────────────────────

/**
 * Generate _locale.ts: the async locale() resolver with dynamic import and caching.
 */
export async function generateLocaleResolverFile(
  outputDir: string,
  collections: SplitCollectionMeta[],
  locales: string[],
  fallbackMap: Record<string, string>
): Promise<void> {
  const localeUnion = locales.map((l) => `"${l}"`).join(" | ");

  let output = `// Auto-generated by contenz - DO NOT EDIT\n`;
  for (const col of collections) {
    output += `import type { ${col.entryTypeName} } from "./_types.js";\n`;
  }
  output += "\n";

  // LocaleCollections interface
  output += `export interface LocaleCollections {\n`;
  for (const col of collections) {
    output += `  ${col.name}: Record<string, ${col.entryTypeName}>;\n`;
  }
  output += `}\n\n`;

  // Cache
  output += `const _cache = new Map<string, LocaleCollections>();\n\n`;

  // locale() function
  output += `/**\n`;
  output += ` * Get all collections for a specific locale.\n`;
  output += ` * Uses dynamic import() so only the requested locale is loaded.\n`;
  output += ` *\n`;
  output += ` * @example\n`;
  output += ` * const { faq } = await locale("en");\n`;
  output += ` * const entry = faq["moq"];\n`;
  output += ` */\n`;
  output += `export async function locale(loc: ${localeUnion} | (string & {})): Promise<LocaleCollections> {\n`;
  output += `  const cached = _cache.get(loc);\n`;
  output += `  if (cached) return cached;\n\n`;

  // Dynamic imports
  output += `  const [${collections.map((c) => `${c.name}Mod`).join(", ")}] = await Promise.all([\n`;
  for (const col of collections) {
    output += `    import(\`./$\{loc}/${col.name}.js\`),\n`;
  }
  output += `  ]);\n\n`;

  output += `  const result: LocaleCollections = {\n`;
  for (const col of collections) {
    output += `    ${col.name}: ${col.name}Mod.${col.name},\n`;
  }
  output += `  };\n\n`;

  output += `  _cache.set(loc, result);\n`;
  output += `  return result;\n`;
  output += `}\n\n`;

  // getEntry() function with fallback chain
  const hasFallback = Object.keys(fallbackMap).length > 0;
  output += `/**\n`;
  output += ` * Get a single entry by collection, slug, and locale.\n`;
  if (hasFallback) {
    output += ` * Supports fallback chain resolution.\n`;
  }
  output += ` */\n`;
  output += `export async function getEntry<K extends keyof LocaleCollections>(\n`;
  output += `  collection: K,\n`;
  output += `  slug: string,\n`;
  output += `  loc: string,\n`;
  output += `): Promise<LocaleCollections[K][string] | null> {\n`;
  output += `  try {\n`;
  output += `    const data = await locale(loc);\n`;
  output += `    const entry = data[collection][slug];\n`;
  output += `    if (entry) return entry;\n`;
  output += `  } catch {\n`;
  output += `    // Locale directory doesn't exist\n`;
  output += `  }\n`;

  if (hasFallback) {
    output += `\n  // Fallback chain\n`;
    output += `  const fallbackMap: Record<string, string> = ${JSON.stringify(fallbackMap)};\n`;
    output += `  let fallback = fallbackMap[loc] ?? fallbackMap.__default;\n`;
    output += `  const visited = new Set<string>([loc]);\n`;
    output += `  while (fallback && !visited.has(fallback)) {\n`;
    output += `    visited.add(fallback);\n`;
    output += `    try {\n`;
    output += `      const fbData = await locale(fallback);\n`;
    output += `      const fbEntry = fbData[collection][slug];\n`;
    output += `      if (fbEntry) return fbEntry;\n`;
    output += `    } catch {\n`;
    output += `      // Fallback locale directory doesn't exist\n`;
    output += `    }\n`;
    output += `    fallback = fallbackMap[fallback] ?? fallbackMap.__default;\n`;
    output += `  }\n`;
  }

  output += `\n  return null;\n`;
  output += `}\n\n`;

  // Locale list
  output += `/** Available locales (detected at build time) */\n`;
  output += `export const locales = [${locales.map((l) => `"${l}"`).join(", ")}] as const;\n`;
  output += `export type Locale = ${localeUnion};\n`;

  await fs.writeFile(path.join(outputDir, "_locale.ts"), output, "utf-8");
}

// ── Root index (index.ts) ───────────────────────────────────────────────────

/**
 * Generate root index.ts for split mode: re-exports types + locale utility.
 */
export async function generateSplitRootIndexFile(
  outputDir: string,
  collections: SplitCollectionMeta[]
): Promise<void> {
  let output = `// Auto-generated by contenz - DO NOT EDIT\n\n`;

  // Re-export all types
  const typeExports: string[] = [];
  for (const col of collections) {
    typeExports.push(col.metaTypeName, col.entryTypeName);
  }
  output += `export type { ${typeExports.join(", ")} } from "./_types.js";\n`;

  // Re-export locale utility
  output += `export { locale, getEntry, locales } from "./_locale.js";\n`;
  output += `export type { Locale, LocaleCollections } from "./_locale.js";\n`;

  await fs.writeFile(path.join(outputDir, "index.ts"), output, "utf-8");
}
