/**
 * Programmatic build: generate content data files.
 * Used by the CLI and by @contenz/core/api.
 */

import fs from "node:fs/promises";
import path from "node:path";

import pMap from "p-map";
import { getContentType, getSchemaForType } from "./config.js";
import {
  type Diagnostic,
  type DiagnosticFormat,
  formatDiagnosticsReport,
  schemaExportMissing,
  schemaLoadFailed,
} from "./diagnostics.js";
import {
  calculateI18nStats,
  type FlatCollectionData,
  generateFlatCollectionFile,
  generateI18nCollectionFile,
  generateIndexFile,
  generateTypeFromZod,
  type I18nCollectionData,
} from "./generator.js";
import {
  generateLocaleIndexFile,
  generateLocaleResolverFile,
  generateSharedTypesFile,
  generateSplitLocaleCollectionFile,
  generateSplitRootIndexFile,
  type SplitCollectionMeta,
} from "./generator-split.js";
import {
  computeCollectionInputHash,
  computeConfigHash,
  getCachedInputHash,
  loadManifest,
  type ManifestCollectionEntry,
  mergeManifest,
  saveManifest,
} from "./manifest.js";
import { parseContentFile, parseFileName } from "./parser.js";
import {
  addDocumentsToIndex,
  buildSearchDocument,
  collectMetaFieldNames,
  createSearchIndex,
  discardDocuments,
  loadSearchIndex,
  type SearchDocument,
  saveSearchIndex,
} from "./search-index.js";
import { validateMeta } from "./validator.js";
import { type CollectionContext, createWorkspace } from "./workspace.js";

const BUILD_CONCURRENCY = 4;

export interface BuildResult {
  success: boolean;
  errors: number;
  report: string;
  diagnostics: Diagnostic[];
  generated: string[];
}

export interface BuildOptions {
  cwd: string;
  format?: DiagnosticFormat;
  sources?: string[];
  /** @deprecated Use `sources` instead. */
  dir?: string;
  /** Rebuild all collections, ignore manifest cache */
  force?: boolean;
  /** Report what would be generated without writing files or updating manifest */
  dryRun?: boolean;
}

/** Index metadata for one collection, used to generate index.ts */
interface IndexMeta {
  name: string;
  types?: string[];
  hasI18n: boolean;
  metaTypeName?: string;
}

async function generateMultiTypeCollectionFile(
  outputPath: string,
  _collectionName: string,
  typeGroups: Map<string, Map<string, I18nCollectionData | FlatCollectionData>>,
  i18n: boolean,
  locales: string[],
  schemaModule: Record<string, unknown>
): Promise<void> {
  let output = `// Auto-generated by contenz - DO NOT EDIT
// Run: contenz build

`;

  for (const typeName of typeGroups.keys()) {
    if (typeName === "default") continue;
    const pascalName = typeName.charAt(0).toUpperCase() + typeName.slice(1);
    const metaTypeName = `${pascalName}Meta`;
    const schema = schemaModule[`${typeName}Meta`] || schemaModule[typeName];
    if (schema && typeof schema === "object" && "_def" in schema) {
      output += generateTypeFromZod(schema as import("zod").ZodTypeAny, metaTypeName);
      output += "\n\n";
    } else {
      output += `export interface ${metaTypeName} {\n  [key: string]: unknown;\n}\n\n`;
    }
  }

  const defaultTypeName = "default";
  for (const [typeName, itemsMap] of typeGroups) {
    if (typeName === defaultTypeName) continue;
    const pascalName = typeName.charAt(0).toUpperCase() + typeName.slice(1);
    const items = Array.from(itemsMap.values()).sort((a, b) => a.slug.localeCompare(b.slug));

    if (i18n) {
      output += `export interface ${pascalName}Entry extends ${pascalName}Meta {
  slug: string;
  file: string;
}

export interface ${pascalName}Item {
  slug: string;
  locales: {
${locales.map((l) => `    ${l}?: ${pascalName}Entry;`).join("\n")}
  };
}

export const ${typeName}s: Record<string, ${pascalName}Item> = `;
      const dataObj: Record<string, unknown> = {};
      for (const item of items as I18nCollectionData[]) {
        const itemData: Record<string, unknown> = { slug: item.slug, locales: {} };
        for (const [locale, entry] of Object.entries(item.locales)) {
          (itemData.locales as Record<string, unknown>)[locale] = {
            slug: item.slug,
            file: entry.file,
            ...entry.meta,
          };
        }
        dataObj[item.slug] = itemData;
      }
      output += JSON.stringify(dataObj, null, 2);
      output += ";\n\n";
      output += `export const ${typeName}sSlugs = Object.keys(${typeName}s) as (keyof typeof ${typeName}s)[];\n\n`;
      const stats = calculateI18nStats(items as I18nCollectionData[]);
      output += `export const ${typeName}sStats = ${JSON.stringify(stats, null, 2)};\n\n`;
    } else {
      output += `export interface ${pascalName}Entry extends ${pascalName}Meta {
  slug: string;
  file: string;
}

export const ${typeName}s: Record<string, ${pascalName}Entry> = `;
      const dataObj: Record<string, unknown> = {};
      for (const item of items as FlatCollectionData[]) {
        dataObj[item.slug] = { slug: item.slug, file: item.file, ...item.meta };
      }
      output += JSON.stringify(dataObj, null, 2);
      output += ";\n\n";
      output += `export const ${typeName}sSlugs = Object.keys(${typeName}s) as (keyof typeof ${typeName}s)[];\n\n`;
      output += `export const ${typeName}sStats = { total: ${items.length} };\n\n`;
    }
  }

  await fs.writeFile(outputPath, output, "utf-8");
}

async function processOneCollection(
  ctx: CollectionContext,
  outputDir: string,
  dryRun: boolean
): Promise<
  | {
      ok: true;
      indexMeta: IndexMeta;
      outputName: string;
      diagnostics: Diagnostic[];
      inputHash: string;
      contentFiles: string[];
      searchDocs: SearchDocument[];
      /** i18n items data (available when i18n enabled, for split output) */
      i18nItems?: I18nCollectionData[];
      /** Detected locales for this collection */
      detectedLocales?: string[];
      /** Default schema for type generation */
      defaultSchema?: import("zod").ZodSchema;
    }
  | { ok: false; diagnostics: Diagnostic[] }
> {
  const diagnostics: Diagnostic[] = [];
  const searchDocs: SearchDocument[] = [];
  const { name: collectionName, collectionPath, config, schema: schemaModule, contentFiles } = ctx;

  if (!schemaModule) {
    diagnostics.push(schemaLoadFailed("build", collectionName));
    return { ok: false, diagnostics };
  }

  const rawSchema = schemaModule.meta;
  if (!rawSchema) {
    diagnostics.push(schemaExportMissing("build", collectionName));
    return { ok: false, diagnostics };
  }
  const defaultSchema = rawSchema as import("zod").ZodSchema;

  const effectiveConfig = {
    ...config,
    types: config.types?.length ? config.types : schemaModule.types,
  };

  const typeGroups = new Map<string, Map<string, I18nCollectionData | FlatCollectionData>>();
  const defaultTypeName = "default";
  let parseErrors = 0;
  const detectedLocales = new Set<string>();

  for (const file of contentFiles) {
    const filePath = path.join(collectionPath, file);
    const parsed = parseFileName(file, effectiveConfig.i18n, effectiveConfig.slugPattern);
    if (!parsed) {
      diagnostics.push({
        code: "CONTENT_FILE_SKIPPED",
        severity: "warning",
        category: "content",
        message: "Skipped file because it does not match the expected naming pattern.",
        source: "build",
        collection: collectionName,
        file,
      });
      continue;
    }
    try {
      const result = await parseContentFile(filePath, effectiveConfig);
      const contentType = getContentType(file, effectiveConfig) ?? defaultTypeName;
      const schema =
        contentType !== defaultTypeName
          ? (getSchemaForType(schemaModule, contentType) ?? defaultSchema)
          : defaultSchema;
      const validation = validateMeta(result.meta, schema, file);
      if (!validation.valid) {
        parseErrors++;
        for (const err of validation.errors) {
          diagnostics.push({
            code: "META_VALIDATION_FAILED",
            severity: "error",
            category: "validation",
            message: err.message,
            source: "build",
            collection: collectionName,
            file,
            field: err.field,
          });
        }
        continue;
      }
      if (!typeGroups.has(contentType)) typeGroups.set(contentType, new Map());
      const itemsMap = typeGroups.get(contentType);
      if (!itemsMap) {
        parseErrors++;
        diagnostics.push({
          code: "BUILD_TYPE_GROUP_FAILED",
          severity: "error",
          category: "build",
          message: "Internal error creating collection type group.",
          source: "build",
          collection: collectionName,
          file,
        });
        continue;
      }
      if (effectiveConfig.i18n && parsed.locale) {
        detectedLocales.add(parsed.locale);
        if (!itemsMap.has(parsed.slug)) {
          itemsMap.set(parsed.slug, { slug: parsed.slug, locales: {} });
        }
        const item = itemsMap.get(parsed.slug) as I18nCollectionData;
        item.locales[parsed.locale] = { file, meta: result.meta };
      } else {
        itemsMap.set(parsed.slug, {
          slug: parsed.slug,
          file,
          meta: result.meta,
        } as FlatCollectionData);
      }

      // Collect search document for this parsed content file
      searchDocs.push(
        buildSearchDocument(
          collectionName,
          parsed.slug,
          parsed.locale,
          file,
          result.meta,
          result.body
        )
      );
    } catch (error) {
      parseErrors++;
      diagnostics.push({
        code: "CONTENT_PARSE_FAILED",
        severity: "error",
        category: "content",
        message: error instanceof Error ? error.message : String(error),
        source: "build",
        collection: collectionName,
        file,
      });
    }
  }

  if (parseErrors > 0) {
    return { ok: false, diagnostics };
  }

  const types = effectiveConfig.types?.map((t) => t.name) ?? [];
  const locales = [...detectedLocales].sort();
  const collectionOutputPath = path.join(outputDir, `${collectionName}.ts`);
  const inputHash = await computeCollectionInputHash(
    collectionPath,
    contentFiles,
    effectiveConfig.extensions
  );

  if (types.length > 0) {
    if (!dryRun) {
      await generateMultiTypeCollectionFile(
        collectionOutputPath,
        collectionName,
        typeGroups,
        effectiveConfig.i18n,
        locales,
        schemaModule as Record<string, unknown>
      );
    }
    return {
      ok: true,
      indexMeta: { name: collectionName, types, hasI18n: effectiveConfig.i18n },
      outputName: `${collectionName}.ts`,
      diagnostics,
      inputHash,
      contentFiles,
      searchDocs,
    };
  }

  const itemsMap = typeGroups.get(defaultTypeName) ?? new Map();
  const items = Array.from(itemsMap.values()).sort((a, b) => a.slug.localeCompare(b.slug));
  const metaTypeName =
    ((schemaModule as Record<string, unknown>).metaTypeName as string | undefined) ??
    `${collectionName.charAt(0).toUpperCase() + collectionName.slice(1)}Meta`;

  if (effectiveConfig.i18n) {
    const i18nItems = items as I18nCollectionData[];
    const ri = effectiveConfig.resolvedI18n;
    const stats = calculateI18nStats(i18nItems);

    if (ri?.coverageThreshold != null && stats.coverage < ri.coverageThreshold) {
      diagnostics.push({
        code: "I18N_COVERAGE_BELOW_THRESHOLD",
        severity: effectiveConfig.strict ? "error" : "warning",
        category: "i18n",
        message: `Translation coverage ${Math.round(stats.coverage * 100)}% is below threshold ${Math.round(ri.coverageThreshold * 100)}%.`,
        source: "build",
        collection: collectionName,
      });
    }

    if (ri?.detectStale && ri.defaultLocale) {
      const sourceLocale = ri.defaultLocale;
      for (const item of i18nItems) {
        const sourceEntry = item.locales[sourceLocale];
        if (!sourceEntry) continue;
        const sourcePath = path.join(collectionPath, sourceEntry.file);
        let sourceMtime: number;
        try {
          sourceMtime = (await fs.stat(sourcePath)).mtimeMs;
        } catch {
          continue;
        }
        for (const [locale, entry] of Object.entries(item.locales)) {
          if (locale === sourceLocale) continue;
          const localePath = path.join(collectionPath, entry.file);
          try {
            const localeMtime = (await fs.stat(localePath)).mtimeMs;
            if (localeMtime < sourceMtime) {
              diagnostics.push({
                code: "I18N_STALE_TRANSLATION",
                severity: effectiveConfig.strict ? "error" : "warning",
                category: "i18n",
                message: `Translation ${entry.file} is older than source ${sourceEntry.file}.`,
                source: "build",
                collection: collectionName,
                file: entry.file,
              });
            }
          } catch {
            // ignore
          }
        }
      }
    }

    // Undeclared locale validation
    if (ri?.locales.length) {
      for (const detectedLocale of detectedLocales) {
        if (!ri.locales.includes(detectedLocale)) {
          diagnostics.push({
            code: "I18N_UNDECLARED_LOCALE",
            severity: "warning",
            category: "i18n",
            message: `Detected locale "${detectedLocale}" is not in the declared locales list [${ri.locales.join(", ")}].`,
            source: "build",
            collection: collectionName,
          });
        }
      }
    }

    // Generate merged output only when outputStrategy is not "split".
    // Split output is handled in runBuild after all collections are processed.
    const isSplit = ri?.outputStrategy === "split";
    if (!dryRun && !isSplit) {
      await generateI18nCollectionFile(
        collectionOutputPath,
        collectionName,
        i18nItems,
        metaTypeName,
        locales,
        defaultSchema,
        ri?.includeFallbackMetadata ? ri : undefined
      );
    }

    return {
      ok: true,
      indexMeta: { name: collectionName, hasI18n: effectiveConfig.i18n, metaTypeName },
      outputName: isSplit ? "" : `${collectionName}.ts`,
      diagnostics,
      inputHash,
      contentFiles,
      searchDocs,
      i18nItems,
      detectedLocales: locales,
      defaultSchema,
    };
  } else {
    if (!dryRun) {
      await generateFlatCollectionFile(
        collectionOutputPath,
        collectionName,
        items as FlatCollectionData[],
        metaTypeName,
        defaultSchema
      );
    }
  }

  return {
    ok: true,
    indexMeta: { name: collectionName, hasI18n: effectiveConfig.i18n, metaTypeName },
    outputName: `${collectionName}.ts`,
    diagnostics,
    inputHash,
    contentFiles,
    searchDocs,
    i18nItems: undefined,
    detectedLocales: undefined,
    defaultSchema: undefined,
  };
}

export async function runBuild(options: BuildOptions): Promise<BuildResult> {
  const diagnostics: Diagnostic[] = [];
  const cwd = path.resolve(process.cwd(), options.cwd ?? ".");
  const format = options.format ?? "pretty";

  // ── Bootstrap via Workspace ──────────────────────────────────────────
  let workspace: Awaited<ReturnType<typeof createWorkspace>>;
  try {
    workspace = await createWorkspace({
      cwd,
      sources: options.sources,
      dir: options.dir,
    });
  } catch (error) {
    diagnostics.push({
      code: "CONFIG_INVALID",
      severity: "error",
      category: "config",
      message: error instanceof Error ? error.message : String(error),
      source: "build",
    });
    return {
      success: false,
      errors: 1,
      report: formatDiagnosticsReport({
        diagnostics,
        format,
        title: "Build diagnostics",
        success: false,
        metadata: { generated: [] },
      }),
      diagnostics,
      generated: [],
    };
  }

  const { resolvedConfig: baseConfig, sources, collections } = workspace;
  const outputDir = path.resolve(cwd, baseConfig.outputDir);

  if (!options.dryRun) {
    await fs.mkdir(outputDir, { recursive: true });
  }

  if (workspace.discoveryErrors.length > 0) {
    for (const error of workspace.discoveryErrors) {
      diagnostics.push({
        code: "DISCOVERY_DUPLICATE_COLLECTION",
        severity: "error",
        category: "discovery",
        message: error,
        source: "build",
      });
    }
    return {
      success: false,
      errors: workspace.discoveryErrors.length,
      report: formatDiagnosticsReport({
        diagnostics,
        format,
        title: "Build diagnostics",
        success: false,
        metadata: { generated: [] },
      }),
      diagnostics,
      generated: [],
    };
  }

  if (collections.length === 0) {
    diagnostics.push({
      code: "DISCOVERY_NO_COLLECTIONS",
      severity: "warning",
      category: "discovery",
      message: "No schema.ts files found in the configured sources.",
      source: "build",
    });
    return {
      success: true,
      errors: 0,
      report: formatDiagnosticsReport({
        diagnostics,
        format,
        title: "Build diagnostics",
        success: true,
        metadata: { generated: [] },
        footer: `Sources: ${sources.join(", ")}\nOutput: ${path.relative(cwd, outputDir)}/`,
      }),
      diagnostics,
      generated: [],
    };
  }

  const force = options.force ?? false;
  const dryRun = options.dryRun ?? false;
  const projectConfigHash = computeConfigHash(baseConfig as unknown as Record<string, unknown>);
  const manifest = !force && !dryRun ? await loadManifest(cwd) : null;

  /** Collections we can skip (cached hash matches, output exists) */
  const skipped: { name: string; outputName: string; indexMeta: IndexMeta }[] = [];
  /** Collections we need to build */
  const toBuild: { ctx: CollectionContext; inputHash: string }[] = [];

  for (const ctx of collections) {
    const inputHash = await computeCollectionInputHash(
      ctx.collectionPath,
      ctx.contentFiles,
      ctx.config.extensions
    );

    let skip = false;
    if (!force && !dryRun && manifest) {
      const cachedHash = getCachedInputHash(
        manifest,
        cwd,
        baseConfig.outputDir,
        sources,
        ctx.name,
        projectConfigHash
      );
      const outputPath = path.join(outputDir, `${ctx.name}.ts`);
      try {
        await fs.access(outputPath);
        if (cachedHash === inputHash) skip = true;
      } catch {
        // output missing, rebuild
      }
    }
    if (skip) {
      const entry = manifest?.collections.find((c) => c.name === ctx.name);
      const indexMeta = entry?.indexMeta ?? {
        name: ctx.name,
        hasI18n: ctx.config.i18n,
        types: ctx.config.types?.map((t) => t.name),
      };
      skipped.push({
        name: ctx.name,
        outputName: `${ctx.name}.ts`,
        indexMeta: indexMeta as IndexMeta,
      });
    } else {
      toBuild.push({ ctx, inputHash });
    }
  }

  const results = await pMap(toBuild, ({ ctx }) => processOneCollection(ctx, outputDir, dryRun), {
    concurrency: BUILD_CONCURRENCY,
  });

  for (const r of results) {
    diagnostics.push(...r.diagnostics);
  }

  const succeeded = results.filter(
    (
      r
    ): r is {
      ok: true;
      indexMeta: IndexMeta;
      outputName: string;
      diagnostics: Diagnostic[];
      inputHash: string;
      contentFiles: string[];
      searchDocs: SearchDocument[];
      i18nItems?: I18nCollectionData[];
      detectedLocales?: string[];
      defaultSchema?: import("zod").ZodSchema;
    } => r.ok
  );

  const indexMetaList: IndexMeta[] = [
    ...skipped.map((s) => s.indexMeta),
    ...succeeded.map((r) => r.indexMeta),
  ].sort((a, b) => a.name.localeCompare(b.name));

  const generated: string[] = [
    ...skipped.map((s) => s.outputName),
    ...succeeded.map((r) => r.outputName),
  ];

  // Determine if any collection uses split output strategy
  const useSplitOutput = baseConfig.resolvedI18n?.outputStrategy === "split";

  if (!dryRun && useSplitOutput) {
    // Collect all split-eligible collections
    const splitCollections: {
      meta: SplitCollectionMeta;
      items: I18nCollectionData[];
    }[] = [];
    const allDetectedLocales = new Set<string>();

    for (const r of succeeded) {
      if (r.i18nItems && r.detectedLocales) {
        const entryTypeName = (
          r.indexMeta.metaTypeName ??
          `${r.indexMeta.name.charAt(0).toUpperCase() + r.indexMeta.name.slice(1)}Meta`
        ).replace("Meta", "Entry");
        splitCollections.push({
          meta: {
            name: r.indexMeta.name,
            metaTypeName:
              r.indexMeta.metaTypeName ??
              `${r.indexMeta.name.charAt(0).toUpperCase() + r.indexMeta.name.slice(1)}Meta`,
            entryTypeName,
            schema: r.defaultSchema as import("zod").ZodTypeAny | undefined,
          },
          items: r.i18nItems,
        });
        for (const l of r.detectedLocales) allDetectedLocales.add(l);
      }
    }

    const sortedLocales = [...allDetectedLocales].sort();
    const fallbackMap = baseConfig.resolvedI18n?.fallbackMap ?? {};
    const includeFallbackMeta = baseConfig.resolvedI18n?.includeFallbackMetadata === true;

    // Generate shared types
    await generateSharedTypesFile(
      outputDir,
      splitCollections.map((c) => c.meta)
    );
    generated.push("_types.ts");

    // Generate per-locale collection files and locale index files
    for (const locale of sortedLocales) {
      for (const col of splitCollections) {
        await generateSplitLocaleCollectionFile(
          outputDir,
          locale,
          col.meta.name,
          col.items,
          col.meta.entryTypeName,
          fallbackMap,
          includeFallbackMeta
        );
        generated.push(`${locale}/${col.meta.name}.ts`);
      }
      await generateLocaleIndexFile(
        outputDir,
        locale,
        splitCollections.map((c) => c.meta)
      );
      generated.push(`${locale}/index.ts`);
    }

    // Generate locale resolver
    await generateLocaleResolverFile(
      outputDir,
      splitCollections.map((c) => c.meta),
      sortedLocales,
      fallbackMap
    );
    generated.push("_locale.ts");

    // Generate split root index
    await generateSplitRootIndexFile(
      outputDir,
      splitCollections.map((c) => c.meta)
    );
    generated.push("index.ts");

    // Also generate merged files for any non-i18n collections
    const nonI18nMeta = indexMetaList.filter((m) => !m.hasI18n);
    if (nonI18nMeta.length > 0) {
      // Non-i18n collections still get their merged output
      // The split root index already covers types; flat collections need a separate export
    }
  } else if (!dryRun) {
    await generateIndexFile(
      path.join(outputDir, "index.ts"),
      indexMetaList.map((m) => ({
        name: m.name,
        types: m.types,
        hasI18n: m.hasI18n,
        metaTypeName: m.metaTypeName,
      }))
    );
    generated.push("index.ts");
  } else {
    generated.push("index.ts");
  }

  if (!dryRun && succeeded.length > 0) {
    const updates: ManifestCollectionEntry[] = succeeded.map((r) => ({
      name: r.indexMeta.name,
      inputHash: r.inputHash,
      outputFiles: [r.outputName],
      indexMeta: r.indexMeta,
    }));
    const merged = mergeManifest(
      manifest,
      cwd,
      baseConfig.outputDir,
      sources,
      updates,
      projectConfigHash
    );
    await saveManifest(merged);

    // ── Incremental search index update ──────────────────────────────
    // Collect all new search documents from rebuilt collections
    const allNewDocs = succeeded.flatMap((r) => r.searchDocs);
    const allMetaFields = collectMetaFieldNames(allNewDocs);

    // Try loading the existing index for incremental update.
    // On force builds, always start fresh to avoid duplicate IDs.
    let searchIndex = force ? null : await loadSearchIndex(cwd);
    if (searchIndex) {
      // Discard documents we're about to re-add (same IDs = same collection:slug:locale)
      const idsToRemove = allNewDocs.map((d) => d.id);
      discardDocuments(searchIndex, idsToRemove);
    }

    if (!searchIndex) {
      // No existing index or force rebuild — create from scratch
      searchIndex = createSearchIndex(allMetaFields);
    }

    addDocumentsToIndex(searchIndex, allNewDocs);
    await saveSearchIndex(cwd, searchIndex, allMetaFields);
  }

  const failedCount = results.length - succeeded.length;
  if (failedCount > 0) {
    return {
      success: false,
      errors: failedCount,
      report: formatDiagnosticsReport({
        diagnostics,
        format,
        title: "Build diagnostics",
        success: false,
        metadata: { generated },
        footer: `Sources: ${sources.join(", ")}\nOutput: ${path.relative(cwd, outputDir)}/`,
      }),
      diagnostics,
      generated,
    };
  }

  return {
    success: true,
    errors: 0,
    report: formatDiagnosticsReport({
      diagnostics,
      format,
      title: "Build diagnostics",
      success: true,
      metadata: { generated },
      footer: `Sources: ${sources.join(", ")}\nOutput: ${path.relative(cwd, outputDir)}/`,
    }),
    diagnostics,
    generated,
  };
}
