/**
 * Programmatic build: generate content data files.
 * Used by the CLI and by @contenz/core/api.
 */

import fs from "node:fs/promises";
import path from "node:path";

import pMap from "p-map";

import {
  getContentType,
  getSchemaForType,
  readProjectConfigFileRaw,
  resolveConfig,
} from "./config.js";
import {
  configInvalid,
  contentFileSkipped,
  contentParseFailed,
  type Diagnostic,
  type DiagnosticFormat,
  discoveryError,
  formatDiagnosticsReport,
  i18nDiagnostic,
  metaValidationFailed,
  schemaExportMissing,
  schemaLoadFailed,
} from "./diagnostics.js";
import {
  generateLocaleIndexFile,
  generateLocaleResolverFile,
  generateSharedTypesFile,
  generateSplitLocaleCollectionFile,
  generateSplitRootIndexFile,
  type SplitCollectionMeta,
} from "./generator-split.js";
import {
  buildFlatDataObject,
  buildI18nDataObject,
  buildMultiTypeDataObject,
  buildRawI18nDataObject,
  calculateI18nStats,
  type FlatCollectionData,
  generateFlatCollectionFile,
  generateI18nCollectionFile,
  generateIndexFile,
  generateTypeFromZod,
  type I18nCollectionData,
} from "./generator.js";
import { isZodObject } from "./introspect.js";
import {
  computeCollectionInputHash,
  computeConfigHash,
  getCachedInputHash,
  loadManifest,
  type ManifestCollectionEntry,
  mergeManifest,
  saveManifest,
} from "./manifest.js";
import { parseContentFile, parseFileName } from "./parser.js";
import {
  addDocumentsToIndex,
  buildSearchDocument,
  collectMetaFieldNames,
  createSearchIndex,
  discardDocuments,
  loadSearchIndex,
  type SearchDocument,
  saveSearchIndex,
} from "./search-index.js";
import { validateMeta } from "./validator.js";
import { type CollectionContext, createWorkspace } from "./workspace.js";

const BUILD_CONCURRENCY = 4;

/** Public content manifest written to the output dir (v1: file + hash only). */
export interface ContentManifest {
  version: 1;
  builtAt: string;
  collections: Record<
    string,
    { file: string; hash: string; slugs: string[]; locales?: string[] }
  >;
}

/**
 * Read slugs/locales back from a previously emitted collection JSON file.
 * Used for incrementally-skipped collections (no re-parse needed).
 * Returns empty slugs when the file is missing or unparsable (pre-upgrade
 * outputs); the next full build repairs it.
 */
async function readEmittedJsonIndex(
  outputDir: string,
  jsonName: string,
  multiType: boolean
): Promise<{ slugs: string[]; locales?: string[] }> {
  try {
    const raw = await fs.readFile(path.join(outputDir, jsonName), "utf-8");
    const data = JSON.parse(raw) as Record<string, unknown>;
    const groups: Record<string, unknown>[] = multiType
      ? Object.values(data).filter(
          (v): v is Record<string, unknown> => !!v && typeof v === "object"
        )
      : [data];
    const slugs = [
      ...new Set(groups.flatMap((group) => Object.keys(group))),
    ].sort((a, b) => a.localeCompare(b));
    const localeSet = new Set<string>();
    for (const group of groups) {
      for (const value of Object.values(group)) {
        if (!value || typeof value !== "object") continue;
        const locales = (value as { locales?: unknown }).locales;
        if (locales && typeof locales === "object") {
          for (const locale of Object.keys(locales)) {
            localeSet.add(locale);
          }
        }
      }
    }
    return {
      slugs,
      locales: localeSet.size > 0 ? [...localeSet].sort() : undefined,
    };
  } catch {
    return { slugs: [] };
  }
}

/**
 * Write the JSON mirror of a collection's generated data.
 * The data object is built by the shared generator builders, so `.ts` and
 * `.json` outputs always carry identical data. Returns the file name.
 */
async function writeCollectionJson(
  outputDir: string,
  collectionName: string,
  data: unknown
): Promise<string> {
  const fileName = `${collectionName}.json`;
  await fs.writeFile(
    path.join(outputDir, fileName),
    `${JSON.stringify(data, null, 2)}\n`,
    "utf-8"
  );
  return fileName;
}

export interface BuildResult {
  success: boolean;
  errors: number;
  report: string;
  diagnostics: Diagnostic[];
  generated: string[];
}

export interface BuildOptions {
  cwd: string;
  format?: DiagnosticFormat;
  sources?: string[];
  /** @deprecated Use `sources` instead. */
  dir?: string;
  /** Rebuild all collections, ignore manifest cache */
  force?: boolean;
  /** Report what would be generated without writing files or updating manifest */
  dryRun?: boolean;
}

/** Index metadata for one collection, used to generate index.ts */
interface IndexMeta {
  name: string;
  types?: string[];
  hasI18n: boolean;
  metaTypeName?: string;
}

async function generateMultiTypeCollectionFile(
  outputPath: string,
  _collectionName: string,
  typeGroups: Map<string, Map<string, I18nCollectionData | FlatCollectionData>>,
  i18n: boolean,
  locales: string[],
  schemaModule: Record<string, unknown>
): Promise<void> {
  let output = `// Auto-generated by contenz - DO NOT EDIT
// Run: contenz build

`;

  for (const typeName of typeGroups.keys()) {
    if (typeName === "default") continue;
    const pascalName = typeName.charAt(0).toUpperCase() + typeName.slice(1);
    const metaTypeName = `${pascalName}Meta`;
    const schema = schemaModule[`${typeName}Meta`] || schemaModule[typeName];
    if (schema && isZodObject(schema as import("zod").ZodSchema)) {
      output += generateTypeFromZod(
        schema as import("zod").ZodTypeAny,
        metaTypeName
      );
      output += "\n\n";
    } else {
      output += `export interface ${metaTypeName} {\n  [key: string]: unknown;\n}\n\n`;
    }
  }

  const defaultTypeName = "default";
  for (const [typeName, itemsMap] of typeGroups) {
    if (typeName === defaultTypeName) continue;
    const pascalName = typeName.charAt(0).toUpperCase() + typeName.slice(1);
    const items = Array.from(itemsMap.values()).sort((a, b) =>
      a.slug.localeCompare(b.slug)
    );

    if (i18n) {
      output += `export interface ${pascalName}Entry extends ${pascalName}Meta {
  slug: string;
  file: string;
}

export interface ${pascalName}Item {
  slug: string;
  locales: {
${locales.map((l) => `    ${l}?: ${pascalName}Entry;`).join("\n")}
  };
}

export const ${typeName}s: Record<string, ${pascalName}Item> = `;
      const dataObj = buildRawI18nDataObject(items as I18nCollectionData[]);
      output += JSON.stringify(dataObj, null, 2);
      output += ";\n\n";
      output += `export const ${typeName}sSlugs = Object.keys(${typeName}s) as (keyof typeof ${typeName}s)[];\n\n`;
      const stats = calculateI18nStats(items as I18nCollectionData[]);
      output += `export const ${typeName}sStats = ${JSON.stringify(stats, null, 2)};\n\n`;
    } else {
      output += `export interface ${pascalName}Entry extends ${pascalName}Meta {
  slug: string;
  file: string;
}

export const ${typeName}s: Record<string, ${pascalName}Entry> = `;
      const dataObj = buildFlatDataObject(items as FlatCollectionData[]);
      output += JSON.stringify(dataObj, null, 2);
      output += ";\n\n";
      output += `export const ${typeName}sSlugs = Object.keys(${typeName}s) as (keyof typeof ${typeName}s)[];\n\n`;
      output += `export const ${typeName}sStats = { total: ${items.length} };\n\n`;
    }
  }

  await fs.writeFile(outputPath, output, "utf-8");
}

async function processOneCollection(
  ctx: CollectionContext,
  outputDir: string,
  dryRun: boolean,
  extraHashInputs: readonly string[],
  hooks?: import("./types.js").ContenzConfig["hooks"]
): Promise<
  | {
      ok: true;
      indexMeta: IndexMeta;
      outputName: string;
      /** JSON mirror file name (always `<collection>.json`) */
      jsonName: string;
      /** Emitted slugs (mirrors output, excludes unrouted default group) */
      slugs: string[];
      /** Detected locales (i18n collections only) */
      locales?: string[];
      diagnostics: Diagnostic[];
      inputHash: string;
      contentFiles: string[];
      searchDocs: SearchDocument[];
      /** i18n items data (available when i18n enabled, for split output) */
      i18nItems?: I18nCollectionData[];
      /** Detected locales for this collection */
      detectedLocales?: string[];
      /** Default schema for type generation */
      defaultSchema?: import("zod").ZodSchema;
    }
  | { ok: false; diagnostics: Diagnostic[] }
> {
  const diagnostics: Diagnostic[] = [];
  const searchDocs: SearchDocument[] = [];
  const {
    name: collectionName,
    collectionPath,
    config,
    schema: schemaModule,
    contentFiles,
  } = ctx;

  if (!schemaModule && ctx.kind !== "single") {
    diagnostics.push(schemaLoadFailed("build", collectionName));
    return { ok: false, diagnostics };
  }

  const rawSchema = schemaModule?.meta;
  if (!rawSchema && ctx.kind !== "single") {
    diagnostics.push(schemaExportMissing("build", collectionName));
    return { ok: false, diagnostics };
  }
  // Singles without an inline schema build unvalidated (info, not error).
  if (ctx.kind === "single" && !rawSchema) {
    diagnostics.push({
      code: "SINGLE_UNVALIDATED",
      severity: "info",
      category: "schema",
      message: `Single "${collectionName}" has no schema; meta is unchecked.`,
      source: "build",
      collection: collectionName,
    });
  }
  const defaultSchema = rawSchema;

  const effectiveConfig = {
    ...config,
    types: config.types?.length ? config.types : schemaModule?.types,
  };

  const typeGroups = new Map<
    string,
    Map<string, I18nCollectionData | FlatCollectionData>
  >();
  const defaultTypeName = "default";
  let parseErrors = 0;
  const detectedLocales = new Set<string>();

  for (const file of contentFiles) {
    const filePath = path.join(collectionPath, file);
    const parsed = parseFileName(
      file,
      effectiveConfig.i18n,
      effectiveConfig.slugPattern
    );
    if (!parsed) {
      diagnostics.push(
        contentFileSkipped(
          { source: "build", collection: collectionName },
          file
        )
      );
      continue;
    }
    try {
      const result = await parseContentFile(filePath, effectiveConfig);

      // Hooks
      if (hooks?.transformItem) {
        await hooks.transformItem(result, collectionName);
      }

      // Compute fields
      if (schemaModule?.computed) {
        for (const [key, computeFn] of Object.entries(schemaModule.computed)) {
          try {
            result.meta[key] = await computeFn(result);
          } catch (err) {
            parseErrors++;
            diagnostics.push(
              contentParseFailed(
                { source: "build", collection: collectionName, file },
                `Failed to compute field "${key}": ${err instanceof Error ? err.message : String(err)}`
              )
            );
          }
        }
      }

      const contentType =
        getContentType(file, effectiveConfig) ?? defaultTypeName;
      const schema =
        contentType !== defaultTypeName && schemaModule
          ? (getSchemaForType(schemaModule, contentType) ?? defaultSchema)
          : defaultSchema;
      if (schema) {
        const validation = validateMeta(result.meta, schema, file);
        if (!validation.valid) {
          parseErrors++;
          for (const err of validation.errors) {
            diagnostics.push(
              metaValidationFailed(
                { source: "build", collection: collectionName, file },
                err.message,
                err.field
              )
            );
          }
          continue;
        }
      }
      if (!typeGroups.has(contentType)) typeGroups.set(contentType, new Map());
      const itemsMap = typeGroups.get(contentType);
      if (!itemsMap) {
        parseErrors++;
        diagnostics.push({
          code: "BUILD_TYPE_GROUP_FAILED",
          severity: "error",
          category: "build",
          message: "Internal error creating collection type group.",
          source: "build",
          collection: collectionName,
          file,
        });
        continue;
      }
      if (effectiveConfig.i18n && parsed.locale) {
        detectedLocales.add(parsed.locale);
        if (!itemsMap.has(parsed.slug)) {
          itemsMap.set(parsed.slug, { slug: parsed.slug, locales: {} });
        }
        const item = itemsMap.get(parsed.slug) as I18nCollectionData;
        item.locales[parsed.locale] = { file, meta: result.meta };
      } else {
        itemsMap.set(parsed.slug, {
          slug: parsed.slug,
          file,
          meta: result.meta,
        });
      }

      // Collect search document for this parsed content file
      searchDocs.push(
        buildSearchDocument(
          collectionName,
          parsed.slug,
          parsed.locale,
          file,
          result.meta,
          result.body
        )
      );
    } catch (error) {
      parseErrors++;
      diagnostics.push(
        contentParseFailed(
          { source: "build", collection: collectionName, file },
          error instanceof Error ? error.message : String(error)
        )
      );
    }
  }

  if (parseErrors > 0) {
    return { ok: false, diagnostics };
  }

  const types = effectiveConfig.types?.map((t) => t.name) ?? [];
  const locales = [...detectedLocales].sort();
  const collectionOutputPath = path.join(outputDir, `${collectionName}.ts`);
  const inputHash = await computeCollectionInputHash(
    collectionPath,
    contentFiles,
    effectiveConfig.extensions,
    extraHashInputs
  );

  if (types.length > 0) {
    if (!dryRun) {
      await generateMultiTypeCollectionFile(
        collectionOutputPath,
        collectionName,
        typeGroups,
        effectiveConfig.i18n,
        locales,
        schemaModule as Record<string, unknown>
      );
      await writeCollectionJson(
        outputDir,
        collectionName,
        buildMultiTypeDataObject(typeGroups, effectiveConfig.i18n)
      );
    }
    return {
      ok: true,
      indexMeta: { name: collectionName, types, hasI18n: effectiveConfig.i18n },
      outputName: `${collectionName}.ts`,
      jsonName: `${collectionName}.json`,
      slugs: [...typeGroups.entries()]
        .filter(([typeName]) => typeName !== defaultTypeName)
        .flatMap(([, itemsMap]) => [...itemsMap.keys()])
        .sort((a, b) => a.localeCompare(b)),
      locales,
      diagnostics,
      inputHash,
      contentFiles,
      searchDocs,
    };
  }

  const itemsMap = typeGroups.get(defaultTypeName) ?? new Map();
  const items = Array.from(itemsMap.values()).sort((a, b) =>
    a.slug.localeCompare(b.slug)
  );
  const metaTypeName =
    schemaModule?.metaTypeName ??
    `${collectionName.charAt(0).toUpperCase() + collectionName.slice(1)}Meta`;

  if (effectiveConfig.i18n) {
    const i18nItems = items as I18nCollectionData[];
    const ri = effectiveConfig.resolvedI18n;
    const stats = calculateI18nStats(i18nItems);

    if (
      ri?.coverageThreshold != null &&
      stats.coverage < ri.coverageThreshold
    ) {
      diagnostics.push(
        i18nDiagnostic(
          "I18N_COVERAGE_BELOW_THRESHOLD",
          effectiveConfig.strict ? "error" : "warning",
          { source: "build", collection: collectionName },
          `Translation coverage ${Math.round(stats.coverage * 100)}% is below threshold ${Math.round(ri.coverageThreshold * 100)}%.`
        )
      );
    }

    if (ri?.detectStale && ri.defaultLocale) {
      const sourceLocale = ri.defaultLocale;
      for (const item of i18nItems) {
        const sourceEntry = item.locales[sourceLocale];
        if (!sourceEntry) continue;
        const sourcePath = path.join(collectionPath, sourceEntry.file);
        let sourceMtime: number;
        try {
          sourceMtime = (await fs.stat(sourcePath)).mtimeMs;
        } catch {
          continue;
        }
        for (const [locale, entry] of Object.entries(item.locales)) {
          if (locale === sourceLocale) continue;
          const localePath = path.join(collectionPath, entry.file);
          try {
            const localeMtime = (await fs.stat(localePath)).mtimeMs;
            if (localeMtime < sourceMtime) {
              diagnostics.push(
                i18nDiagnostic(
                  "I18N_STALE_TRANSLATION",
                  effectiveConfig.strict ? "error" : "warning",
                  {
                    source: "build",
                    collection: collectionName,
                    file: entry.file,
                  },
                  `Translation ${entry.file} is older than source ${sourceEntry.file}.`
                )
              );
            }
          } catch {
            // ignore
          }
        }
      }
    }

    // Undeclared locale validation
    if (ri?.locales.length) {
      for (const detectedLocale of detectedLocales) {
        if (!ri.locales.includes(detectedLocale)) {
          diagnostics.push(
            i18nDiagnostic(
              "I18N_UNDECLARED_LOCALE",
              "warning",
              { source: "build", collection: collectionName },
              `Detected locale "${detectedLocale}" is not in the declared locales list [${ri.locales.join(", ")}].`
            )
          );
        }
      }
    }

    // Generate merged output only when outputStrategy is not "split".
    // Split output is handled in runBuild after all collections are processed.
    const isSplit = ri?.outputStrategy === "split";
    if (!dryRun && !isSplit) {
      await generateI18nCollectionFile(
        collectionOutputPath,
        collectionName,
        i18nItems,
        metaTypeName,
        locales,
        defaultSchema,
        ri
      );
      await writeCollectionJson(
        outputDir,
        collectionName,
        buildI18nDataObject(i18nItems, locales, ri)
      );
    }

    return {
      ok: true,
      indexMeta: {
        name: collectionName,
        hasI18n: effectiveConfig.i18n,
        metaTypeName,
      },
      outputName: isSplit ? "" : `${collectionName}.ts`,
      jsonName: `${collectionName}.json`,
      slugs: i18nItems.map((item) => item.slug),
      locales,
      diagnostics,
      inputHash,
      contentFiles,
      searchDocs,
      i18nItems,
      detectedLocales: locales,
      defaultSchema,
    };
  } else {
    if (!dryRun) {
      await generateFlatCollectionFile(
        collectionOutputPath,
        collectionName,
        items as FlatCollectionData[],
        metaTypeName,
        defaultSchema
      );
      await writeCollectionJson(
        outputDir,
        collectionName,
        buildFlatDataObject(items as FlatCollectionData[])
      );
    }
  }

  return {
    ok: true,
    indexMeta: {
      name: collectionName,
      hasI18n: effectiveConfig.i18n,
      metaTypeName,
    },
    outputName: `${collectionName}.ts`,
    jsonName: `${collectionName}.json`,
    slugs: (items as FlatCollectionData[]).map((item) => item.slug),
    diagnostics,
    inputHash,
    contentFiles,
    searchDocs,
    i18nItems: undefined,
    detectedLocales: undefined,
    defaultSchema: undefined,
  };
}

export async function runBuild(options: BuildOptions): Promise<BuildResult> {
  const diagnostics: Diagnostic[] = [];
  const cwd = path.resolve(process.cwd(), options.cwd ?? ".");
  const format = options.format ?? "pretty";

  // ── Bootstrap via Workspace ──────────────────────────────────────────
  let workspace: Awaited<ReturnType<typeof createWorkspace>>;
  try {
    workspace = await createWorkspace({
      cwd,
      sources: options.sources,
      dir: options.dir,
    });
  } catch (error) {
    diagnostics.push(
      configInvalid(
        "build",
        error instanceof Error ? error.message : String(error)
      )
    );
    return {
      success: false,
      errors: 1,
      report: formatDiagnosticsReport({
        diagnostics,
        format,
        title: "Build diagnostics",
        success: false,
        metadata: { generated: [] },
      }),
      diagnostics,
      generated: [],
    };
  }

  const {
    resolvedConfig: baseConfig,
    sources,
    collections,
    singles,
  } = workspace;
  const outputDir = path.resolve(cwd, baseConfig.outputDir);

  if (!options.dryRun) {
    await fs.mkdir(outputDir, { recursive: true });
  }

  if (workspace.discoveryErrors.length > 0) {
    for (const error of workspace.discoveryErrors) {
      diagnostics.push(discoveryError("build", error));
    }
    return {
      success: false,
      errors: workspace.discoveryErrors.length,
      report: formatDiagnosticsReport({
        diagnostics,
        format,
        title: "Build diagnostics",
        success: false,
        metadata: { generated: [] },
      }),
      diagnostics,
      generated: [],
    };
  }

  if (workspace.projectConfig.hooks?.beforeBuild) {
    await workspace.projectConfig.hooks.beforeBuild(workspace);
  }

  // Singles build through the same pipeline (one-slug collections).
  const allContexts = [...collections, ...singles];

  if (allContexts.length === 0) {
    diagnostics.push({
      code: "DISCOVERY_NO_COLLECTIONS",
      severity: "warning",
      category: "discovery",
      message: "No collections or singles found in the configured sources.",
      source: "build",
    });
    return {
      success: true,
      errors: 0,
      report: formatDiagnosticsReport({
        diagnostics,
        format,
        title: "Build diagnostics",
        success: true,
        metadata: { generated: [] },
        footer: `Sources: ${sources.join(", ")}\nOutput: ${path.relative(cwd, outputDir)}/`,
      }),
      diagnostics,
      generated: [],
    };
  }

  const force = options.force ?? false;
  const dryRun = options.dryRun ?? false;
  const projectConfigHash = computeConfigHash(
    baseConfig as unknown as Record<string, unknown>
  );
  // Raw project config bytes: inline collection schemas are zod objects whose
  // shape is invisible to computeConfigHash, so hash the file itself too.
  const projectConfigRaw = await readProjectConfigFileRaw(cwd);
  const configHashInputs = projectConfigRaw != null ? [projectConfigRaw] : [];
  const manifest = !force && !dryRun ? await loadManifest(cwd) : null;

  /** Collections we can skip (cached hash matches, output exists) */
  const skipped: {
    name: string;
    outputName: string;
    jsonName: string;
    indexMeta: IndexMeta;
    inputHash: string;
    slugs: string[];
    locales?: string[];
  }[] = [];
  /** Collections we need to build */
  const toBuild: { ctx: CollectionContext; inputHash: string }[] = [];

  for (const ctx of allContexts) {
    const inputHash = await computeCollectionInputHash(
      ctx.collectionPath,
      ctx.contentFiles,
      ctx.config.extensions,
      configHashInputs
    );

    let skip = false;
    let skippedSlugs: string[] | undefined;
    let skippedLocales: string[] | undefined;
    if (!force && !dryRun && manifest) {
      const cachedHash = getCachedInputHash(
        manifest,
        cwd,
        baseConfig.outputDir,
        sources,
        ctx.name,
        projectConfigHash
      );
      const outputPath = path.join(outputDir, `${ctx.name}.ts`);
      const jsonPath = path.join(outputDir, `${ctx.name}.json`);
      try {
        await fs.access(outputPath);
        await fs.access(jsonPath);
        if (cachedHash === inputHash) {
          skip = true;
          // Reuse the previously emitted JSON for manifest slugs/locales.
          const entry = manifest?.collections.find((c) => c.name === ctx.name);
          const emitted = await readEmittedJsonIndex(
            outputDir,
            `${ctx.name}.json`,
            (entry?.indexMeta?.types?.length ?? 0) > 0
          );
          skippedSlugs = emitted.slugs;
          skippedLocales = emitted.locales;
        }
      } catch {
        // output missing, rebuild
      }
    }
    if (skip) {
      const entry = manifest?.collections.find((c) => c.name === ctx.name);
      const indexMeta = entry?.indexMeta ?? {
        name: ctx.name,
        hasI18n: ctx.config.i18n,
        types: ctx.config.types?.map((t) => t.name),
      };
      skipped.push({
        name: ctx.name,
        outputName: `${ctx.name}.ts`,
        jsonName: `${ctx.name}.json`,
        indexMeta,
        inputHash,
        slugs: skippedSlugs ?? [],
        locales: skippedLocales,
      });
    } else {
      toBuild.push({ ctx, inputHash });
    }
  }

  const results = await pMap(
    toBuild,
    async ({ ctx }) =>
      processOneCollection(
        ctx,
        outputDir,
        dryRun,
        configHashInputs,
        workspace.projectConfig.hooks
      ),
    {
      concurrency: BUILD_CONCURRENCY,
    }
  );

  for (const r of results) {
    diagnostics.push(...r.diagnostics);
  }

  const succeeded = results.filter(
    (
      r
    ): r is {
      ok: true;
      indexMeta: IndexMeta;
      outputName: string;
      jsonName: string;
      slugs: string[];
      locales?: string[];
      diagnostics: Diagnostic[];
      inputHash: string;
      contentFiles: string[];
      searchDocs: SearchDocument[];
      i18nItems?: I18nCollectionData[];
      detectedLocales?: string[];
      defaultSchema?: import("zod").ZodSchema;
    } => r.ok
  );

  const indexMetaList: IndexMeta[] = [
    ...skipped.map((s) => s.indexMeta),
    ...succeeded.map((r) => r.indexMeta),
  ].sort((a, b) => a.name.localeCompare(b.name));

  const generated: string[] = [
    ...skipped.map((s) => s.outputName),
    ...succeeded.map((r) => r.outputName),
    // JSON mirrors (split collections report outputName "" and get theirs below)
    ...skipped.map((s) => s.jsonName),
    ...succeeded.filter((r) => r.outputName !== "").map((r) => r.jsonName),
  ];

  // Determine if any collection uses split output strategy
  const useSplitOutput = baseConfig.resolvedI18n.outputStrategy === "split";

  if (!dryRun && useSplitOutput) {
    // Collect all split-eligible collections
    const splitCollections: {
      meta: SplitCollectionMeta;
      items: I18nCollectionData[];
    }[] = [];
    const allDetectedLocales = new Set<string>();

    for (const r of succeeded) {
      if (r.i18nItems && r.detectedLocales) {
        const entryTypeName = (
          r.indexMeta.metaTypeName ??
          `${r.indexMeta.name.charAt(0).toUpperCase() + r.indexMeta.name.slice(1)}Meta`
        ).replace("Meta", "Entry");
        splitCollections.push({
          meta: {
            name: r.indexMeta.name,
            metaTypeName:
              r.indexMeta.metaTypeName ??
              `${r.indexMeta.name.charAt(0).toUpperCase() + r.indexMeta.name.slice(1)}Meta`,
            entryTypeName,
            schema: r.defaultSchema,
          },
          items: r.i18nItems,
        });
        for (const l of r.detectedLocales) allDetectedLocales.add(l);
      }
    }

    const sortedLocales = [...allDetectedLocales].sort();
    const i18nConfig = {
      fallbackChains: baseConfig.resolvedI18n.fallbackChains,
      defaultFallbackChain: baseConfig.resolvedI18n.defaultFallbackChain,
    };
    const includeFallbackMeta = baseConfig.resolvedI18n.includeFallbackMetadata;

    // Merged-shape JSON mirrors for split collections (TS output is per-locale).
    for (const col of splitCollections) {
      await writeCollectionJson(
        outputDir,
        col.meta.name,
        buildI18nDataObject(col.items, sortedLocales, baseConfig.resolvedI18n)
      );
      generated.push(`${col.meta.name}.json`);
    }

    // Generate shared types
    await generateSharedTypesFile(
      outputDir,
      splitCollections.map((c) => c.meta)
    );
    generated.push("_types.ts");

    // Generate per-locale collection files and locale index files
    for (const locale of sortedLocales) {
      for (const col of splitCollections) {
        await generateSplitLocaleCollectionFile(
          outputDir,
          locale,
          col.meta.name,
          col.items,
          col.meta.entryTypeName,
          i18nConfig,
          includeFallbackMeta
        );
        generated.push(`${locale}/${col.meta.name}.ts`);
      }
      await generateLocaleIndexFile(
        outputDir,
        locale,
        splitCollections.map((c) => c.meta)
      );
      generated.push(`${locale}/index.ts`);
    }

    // Generate locale resolver
    await generateLocaleResolverFile(
      outputDir,
      splitCollections.map((c) => c.meta),
      sortedLocales,
      i18nConfig
    );
    generated.push("_locale.ts");

    // Generate split root index
    await generateSplitRootIndexFile(
      outputDir,
      splitCollections.map((c) => c.meta)
    );
    generated.push("index.ts");

    // Also generate merged files for any non-i18n collections
    const nonI18nMeta = indexMetaList.filter((m) => !m.hasI18n);
    if (nonI18nMeta.length > 0) {
      // Non-i18n collections still get their merged output
      // The split root index already covers types; flat collections need a separate export
    }
  } else if (!dryRun) {
    await generateIndexFile(
      path.join(outputDir, "index.ts"),
      indexMetaList.map((m) => ({
        name: m.name,
        types: m.types,
        hasI18n: m.hasI18n,
        metaTypeName: m.metaTypeName,
      }))
    );
    generated.push("index.ts");
  } else {
    generated.push("index.ts");
  }

  if (!dryRun && succeeded.length > 0) {
    const updates: ManifestCollectionEntry[] = succeeded.map((r) => ({
      name: r.indexMeta.name,
      inputHash: r.inputHash,
      outputFiles: [r.outputName, r.jsonName],
      indexMeta: r.indexMeta,
    }));
    const merged = mergeManifest(
      manifest,
      cwd,
      baseConfig.outputDir,
      sources,
      updates,
      projectConfigHash
    );
    await saveManifest(merged);

    // ── Incremental search index update ──────────────────────────────
    // Collect all new search documents from rebuilt collections
    const allNewDocs = succeeded.flatMap((r) => r.searchDocs);
    const allMetaFields = collectMetaFieldNames(allNewDocs);

    // --- 8. Update Search Index ---
    const projectConfig = resolveConfig(workspace.projectConfig);
    if (projectConfig.buildSearchIndex) {
      if (
        force ||
        allNewDocs.length > 0 ||
        results.length - succeeded.length > 0
      ) {
        // On force builds, always start fresh to avoid duplicate IDs.
        let searchIndex = force ? null : await loadSearchIndex(cwd);
        if (searchIndex) {
          // Discard documents we're about to re-add (same IDs = same collection:slug:locale)
          const idsToRemove = allNewDocs.map((d) => d.id);
          await discardDocuments(searchIndex, idsToRemove);
        }

        if (!searchIndex) {
          // Create fresh
          searchIndex = await createSearchIndex(allMetaFields);
        }

        await addDocumentsToIndex(searchIndex, allNewDocs);
        await saveSearchIndex(cwd, searchIndex, allMetaFields);
      }
    }
  }

  const failedCount = results.length - succeeded.length;

  // Public content manifest: file + hash per collection (powers fetch-based
  // readers and immutable caching). Only on clean builds; skipped collections
  // keep their previously emitted JSON.
  if (failedCount === 0 && (skipped.length > 0 || succeeded.length > 0)) {
    const manifestCollections: ContentManifest["collections"] = {};
    for (const s of skipped) {
      manifestCollections[s.name] = {
        file: s.jsonName,
        hash: s.inputHash,
        slugs: s.slugs,
        ...(s.locales?.length ? { locales: s.locales } : {}),
      };
    }
    for (const r of succeeded) {
      manifestCollections[r.indexMeta.name] = {
        file: r.jsonName,
        hash: r.inputHash,
        slugs: r.slugs,
        ...(r.locales?.length ? { locales: r.locales } : {}),
      };
    }
    const contentManifest: ContentManifest = {
      version: 1,
      builtAt: new Date().toISOString(),
      collections: manifestCollections,
    };
    if (!dryRun) {
      await fs.writeFile(
        path.join(outputDir, "manifest.json"),
        `${JSON.stringify(contentManifest, null, 2)}\n`,
        "utf-8"
      );
    }
    generated.push("manifest.json");
  }

  const buildResult: BuildResult =
    failedCount > 0
      ? {
          success: false,
          errors: failedCount,
          report: formatDiagnosticsReport({
            diagnostics,
            format,
            title: "Build diagnostics",
            success: false,
            metadata: { generated },
            footer: `Sources: ${sources.join(", ")}\nOutput: ${path.relative(cwd, outputDir)}/`,
          }),
          diagnostics,
          generated,
        }
      : {
          success: true,
          errors: 0,
          report: formatDiagnosticsReport({
            diagnostics,
            format,
            title: "Build diagnostics",
            success: true,
            metadata: { generated },
            footer: `Sources: ${sources.join(", ")}\nOutput: ${path.relative(cwd, outputDir)}/`,
          }),
          diagnostics,
          generated,
        };

  if (workspace.projectConfig.hooks?.afterBuild) {
    await workspace.projectConfig.hooks.afterBuild(buildResult);
  }

  return buildResult;
}
